# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 17:32
from __future__ import unicode_literals

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='TaskCode')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('citation', models.TextField(blank=True, null=True, verbose_name='Citation')),
                ('image', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_location, verbose_name='Image')),
                ('command', models.CharField(max_length=100, verbose_name='Command')),
                ('app_compatibility', models.ManyToManyField(blank=True, related_name='_app_app_compatibility_+', to='app.App')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSlideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.image_upload_location, verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='MyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_location, verbose_name='Logo')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('citations', models.TextField(verbose_name='Citations')),
            ],
        ),
        migrations.CreateModel(
            name='ParamsInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('state', models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=15)),
                ('allowed_format', models.CharField(max_length=100, verbose_name='Allowed Format')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_app', to='app.App')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Section')),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.App')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_queue', 'In Queue'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=15)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('file_input', models.FileField(upload_to='files/input/', verbose_name='File Input')),
                ('file_output', models.FileField(blank=True, upload_to='files/output/', verbose_name='File Output')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='app.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
