# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='citation',
            field=models.TextField(blank=True, null=True, verbose_name='Citation'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='app',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
        migrations.AlterField(
            model_name='app',
            name='taskcode',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TaskCode'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subsection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Section'),
        ),
    ]
