# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramsinput',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Required'),
            preserve_default=False,
        ),
    ]
