# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Institution'),
            preserve_default=False,
        ),
    ]
