# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 17:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180222_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='apps',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
        migrations.AddField(
            model_name='app',
            name='citation',
            field=models.CharField(default='', max_length=10000, verbose_name='Citation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='taskcode',
            field=models.CharField(default='', max_length=100, verbose_name='TaskCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
