# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180308_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='sections',
        ),
        migrations.AddField(
            model_name='section',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.App'),
        ),
    ]
