# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180308_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycompany',
            name='images_slideshow',
        ),
    ]
