# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_mycompany_images_slideshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycompany',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
