# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180317_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramsinput',
            name='info',
            field=models.TextField(default='', verbose_name='Info'),
            preserve_default=False,
        ),
    ]
