# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180224_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='citation',
            field=models.CharField(max_length=1000000, verbose_name='Citation'),
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(max_length=1000000, verbose_name='Description'),
        ),
    ]
