# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_paramsinput_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramsinput',
            name='is_file_input',
            field=models.BooleanField(default=False, verbose_name='Is File Input'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paramsinput',
            name='is_file_output',
            field=models.BooleanField(default=False, verbose_name='Is File Output'),
            preserve_default=False,
        ),
    ]
