# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180325_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskcode',
            field=models.CharField(default='taskcode', max_length=100, verbose_name='TaskCode'),
            preserve_default=False,
        ),
    ]
