# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 19:17
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180228_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_upload_location, verbose_name='Image'),
        ),
    ]
