# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-19 17:02
from __future__ import unicode_literals

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180325_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamInputOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='ParamsInputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('allowed_format', models.CharField(max_length=100, verbose_name='Allowed Format')),
                ('option', models.CharField(max_length=10, verbose_name='Option')),
                ('info', models.TextField(verbose_name='Info')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_file_id', to='app.App')),
            ],
        ),
        migrations.CreateModel(
            name='ParamsInputSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('option', models.CharField(max_length=10, verbose_name='Option')),
                ('info', models.TextField(verbose_name='Info')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_select_id', to='app.App')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_id', to='app.ParamInputOption')),
            ],
        ),
        migrations.CreateModel(
            name='ParamsInputText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('option', models.CharField(max_length=10, verbose_name='Option')),
                ('info', models.TextField(verbose_name='Info')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_text_id', to='app.App')),
            ],
        ),
        migrations.AlterField(
            model_name='imageslideshow',
            name='image',
            field=models.ImageField(upload_to=app.models.image_index_upload_location, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mycompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.image_index_upload_location, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file_input',
            field=models.FileField(upload_to=app.models.file_task_input_upload_location, verbose_name='File Input'),
        ),
        migrations.AlterField(
            model_name='task',
            name='file_output',
            field=models.FileField(blank=True, upload_to=app.models.file_task_output_upload_location, verbose_name='File Output'),
        ),
    ]
