# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 09:04
from __future__ import unicode_literals

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180519_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramsinputfile',
            name='value',
        ),
        migrations.AddField(
            model_name='paramsinputfile',
            name='file_input',
            field=models.FileField(blank=True, upload_to=app.models.file_task_input_upload_location, verbose_name='File Input'),
        ),
        migrations.AddField(
            model_name='paramsinputfile',
            name='file_output',
            field=models.FileField(blank=True, upload_to=app.models.file_task_output_upload_location, verbose_name='File Output'),
        ),
    ]
