# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-20 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180520_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraminputoption',
            name='select',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='select_id', to='app.ParamsInputSelect'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paramsinputselect',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Value'),
        ),
    ]
