# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180520_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCompatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='app',
            name='app_compatibility',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='app.AppCompatibility', to='app.App'),
        ),
        migrations.AddField(
            model_name='appcompatibility',
            name='from_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_app', to='app.App'),
        ),
        migrations.AddField(
            model_name='appcompatibility',
            name='to_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_app', to='app.App'),
        ),
    ]
