# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180522_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppCompatibility',
            new_name='CompatibilityApp',
        ),
    ]
