# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180522_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='compatibility_app',
            field=models.ManyToManyField(blank=True, related_name='_app_compatibility_app_+', to='app.App'),
        ),
    ]
