# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_app_compatibility_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_compatibility',
            field=models.ManyToManyField(blank=True, related_name='_app_app_compatibility_+', to='app.App'),
        ),
        migrations.AlterField(
            model_name='app',
            name='compatibility_app',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='app.CompatibilityApp', to='app.App'),
        ),
    ]
