# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20180522_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibilityapp',
            name='from_app',
        ),
        migrations.RemoveField(
            model_name='compatibilityapp',
            name='to_app',
        ),
        migrations.RemoveField(
            model_name='app',
            name='compatibility_app',
        ),
        migrations.DeleteModel(
            name='CompatibilityApp',
        ),
    ]
