# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_compatibilityapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompatibilityApp',
            new_name='Compatibility',
        ),
    ]
