# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180522_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compatibility',
            name='from_app',
        ),
        migrations.RemoveField(
            model_name='compatibility',
            name='to_app',
        ),
        migrations.DeleteModel(
            name='Compatibility',
        ),
    ]
