# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180522_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_app', to='app.App')),
                ('to_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_app', to='app.App')),
            ],
        ),
    ]
